CREATE TABLE [dbo].[fact_planning_applications] (

	[PlanningApplicationKey] bigint NOT NULL, 
	[ApplicationNumber] varchar(100) NOT NULL, 
	[PlanningAuthorityKey] int NOT NULL, 
	[ApplicationTypeKey] int NOT NULL, 
	[ApplicationStatusKey] int NOT NULL, 
	[DecisionTypeKey] int NOT NULL, 
	[LandUseTypeKey] int NOT NULL, 
	[DateKey] int NOT NULL, 
	[ReceivedDate] date NOT NULL, 
	[DecisionDate] date NULL, 
	[GrantDate] date NULL, 
	[ExpiryDate] date NULL, 
	[ApplicationCount] int NOT NULL, 
	[DecisionRecorded] int NOT NULL, 
	[OneOffHouseFlag] int NULL, 
	[NumResidentialUnits] int NULL, 
	[AreaOfSite] decimal(18,4) NULL, 
	[FloorArea] decimal(18,2) NULL, 
	[Latitude] decimal(9,6) NULL, 
	[Longitude] decimal(9,6) NULL, 
	[ITMEasting] float NULL, 
	[ITMNorthing] float NULL, 
	[DevelopmentDescription] varchar(8000) NULL, 
	[DevelopmentAddress] varchar(2000) NULL, 
	[DevelopmentPostcode] varchar(100) NULL, 
	[ApplicationDetailsURL] varchar(2000) NULL, 
	[SourceETLDate] datetime2(6) NULL, 
	[LoadDate] date NULL, 
	[GoldLoadTimestamp] datetime2(6) NULL
);